<!-- <?php

$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/058f42c6-7f7d-46ff-acac-87fdbd3b78c3.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/097387cb-2acf-4086-a23b-2a72a0db7e07.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/0a163099-2dd7-4e7b-ad02-64900a7f734a.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/1223a607-b3a4-4bf0-8e61-e7a813cd6991.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/14698613-4855-4f6d-8079-f90e559a7eb9.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/16350d11-0f4a-4e70-8d1d-69b034002d25.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/1ed60a0d-1dda-4c02-80ea-47c4d0b71d47.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/22a08d01-80df-402c-b240-ab0d7d6320a2.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/2efffc89-65ca-48ab-919c-e139b6baed1d.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/398e3bc5-01aa-4fef-b149-2a0e83b8ef22.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/42fe020a-6bf3-44a6-8c36-fa6238df4212.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/4d5bc768-7e39-46d8-8282-61167ca59c52.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/51be57b0-be1c-44bc-8770-8febdfa5e2ee.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/55782dbd-bd17-4dcd-b623-5fc8b762def2.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/6b1431e0-f033-42fc-a667-ce903f405555.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/6c854aaf-4b97-4300-9a4e-fa3b352d5d88.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/6e38c93f-c0c5-45ff-aeae-3f23b42f2182.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/74c8106d-305b-4181-9ebe-061c28978cea.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/74d3c97e-e081-4f46-856d-0fcf70e94a81.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/76eb65d8-d185-434b-bd88-5c4bbf105000.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/836c3023-afbd-4861-9eb3-9e0c8905b973.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/8586feb2-206b-427d-9112-f1e368b50da5.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/867f6fb5-3462-4f7a-a251-2311a49708cc.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/87e50788-a17f-4aeb-af69-6660781106e7.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/9aad916a-660c-4bfe-8d25-8353ee804b37.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/a0a4d2a3-191f-4298-be1b-a738bf654d4f.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/a27ce4dd-1414-4832-8741-9fb8c5db93e9.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/a47b128c-cca6-4df7-a414-0b38770f1ae3.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/ae476b87-4a48-49da-b854-2cd75b2d1daa.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/b3244b73-a983-4075-905c-d858a0e1d9be.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/bb579eb3-d946-418f-8b79-6802442cc222.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/bb8eca4f-62fc-46d5-b407-e59eb242a38e.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/bc163b80-2509-4e6b-abc7-9cb0fe91e2b9.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/c4039369-9d1c-4299-8a74-401be69cd46d.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/c6191639-3caf-4dfa-92e1-8190917c70d5.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/c7361412-781f-4f40-94e3-bf84f476b6a8.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/d6d1bba9-7aee-45da-b02e-b9b9c5d134c8.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/e86b926e-c487-44c1-bdc1-980826f2fcaa.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/ec6f7899-b26e-4fcc-824e-dd4db682f6ce.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
$link= 'https://panoptes-uploads.zooniverse.org/production/subject_location/ee24391a-bb21-4edb-8e6a-f2b90e68604c.png';
$destdir = 'testImages/';
$img=file_get_contents($link);
file_put_contents($destdir.substr($link, strrpos($link,'/')), $img);
 -->